### ISSUE TITLE
Crash on starting any game but "continue" works without save game?

### ISSUE THREAD

**Issue by Quix0r** [lincity-ng/lincity-ng#7]
The game crashes all over again on starting a new game (even with or without village):
````
[Thread 0x7ffff20d1700 (LWP 6324) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00000000004127b1 in MainMenu::newGameStartButtonClicked (this=0xcf5860)
    at ../../lincity-ng/src/lincity-ng/MainMenu.cpp:874
874         city->without_trees = (getCheckButton(*currentMenu,"WithoutTrees")->state == CheckButton::STATE_CHECKED);
(gdb) bt
#0  0x00000000004127b1 in MainMenu::newGameStartButtonClicked (this=0xcf5860)
    at ../../lincity-ng/src/lincity-ng/MainMenu.cpp:874
#1  0x000000000046cd85 in Signal<Button*, void>::operator() (arg1=0x14f1a00, this=0x14f1a60)
    at ../../lincity-ng/src/gui/callback/Signal.hpp:88
#2  Button::event (this=0x14f1a00, event=...) at ../../lincity-ng/src/gui/Button.cpp:305
#3  0x0000000000469b78 in Component::eventChild (this=this@entry=0x140e300, child=..., 
    event=..., visible=visible@entry=true) at ../../lincity-ng/src/gui/Component.cpp:101
#4  0x0000000000469c2c in Component::event (this=0x140e300, event=...)
    at ../../lincity-ng/src/gui/Component.cpp:114
#5  0x0000000000469b78 in Component::eventChild (this=this@entry=0x1182aa0, child=..., 
    event=..., visible=visible@entry=true) at ../../lincity-ng/src/gui/Component.cpp:101
#6  0x0000000000469c2c in Component::event (this=0x1182aa0, event=...)
    at ../../lincity-ng/src/gui/Component.cpp:114
#7  0x0000000000469b78 in Component::eventChild (this=this@entry=0x1182660, child=..., 
    event=..., visible=visible@entry=true) at ../../lincity-ng/src/gui/Component.cpp:101
#8  0x0000000000469c2c in Component::event (this=this@entry=0x1182660, event=...)
    at ../../lincity-ng/src/gui/Component.cpp:114
#9  0x000000000046807e in Desktop::event (this=0x1182660, event=...)
    at ../../lincity-ng/src/gui/Desktop.cpp:78
#10 0x00000000004174a8 in MainMenu::run (this=this@entry=0xcf5860)
    at ../../lincity-ng/src/lincity-ng/MainMenu.cpp:1019
#11 0x0000000000459d45 in mainLoop () at ../../lincity-ng/src/lincity-ng/main.cpp:439
#12 0x000000000040a2c7 in main (argc=1, argv=0x7fffffffd248)
    at ../../lincity-ng/src/lincity-ng/main.cpp:608
(gdb) 
````

And full:
````
#0  0x00000000004127b1 in MainMenu::newGameStartButtonClicked (this=0xcf5860)
    at ../../lincity-ng/src/lincity-ng/MainMenu.cpp:874
        city_obj = {with_village = false, without_trees = false}
        city = 0x7fffffffca70
#1  0x000000000046cd85 in Signal<Button*, void>::operator() (arg1=0x14f1a00, this=0x14f1a60)
    at ../../lincity-ng/src/gui/callback/Signal.hpp:88
        i = 
#2  Button::event (this=0x14f1a00, event=...) at ../../lincity-ng/src/gui/Button.cpp:305
        oldState = Button::STATE_CLICKED
#3  0x0000000000469b78 in Component::eventChild (this=this@entry=0x140e300, child=..., 
    event=..., visible=visible@entry=true) at ../../lincity-ng/src/gui/Component.cpp:101
        __PRETTY_FUNCTION__ = "bool Component::eventChild(Child&, const Event&, bool)"
        ev = {type = Event::MOUSEBUTTONUP, mousepos = {x = 73, y = 20.6666565}, mousemove = {
            x = 0, y = 0}, mousebutton = 1, keysym = {scancode = 64 '@', sym = SDLK_LALT, 
            mod = KMOD_NONE, unicode = 0}, inside = true, elapsedTime = 0.100000001}
#4  0x0000000000469c2c in Component::event (this=0x140e300, event=...)
    at ../../lincity-ng/src/gui/Component.cpp:114
        child = @0x14fc188: {position = {x = 1013, y = 40.1111145}, enabled = true, 
          useClipRect = false, clipRect = {p1 = {x = 0, y = 0}, p2 = {x = 0, y = 0}}, 
          component = 0x14f1a00}
        i = {<std::iterator<std::random_access_iterator_tag, Child, long, Child*, Child&>> = {<No data fields>}, current = {position = {x = 2.1860256e-43, y = 0}, enabled = 65, 
            useClipRect = false, clipRect = {p1 = {x = 0, y = 1.40129846e-45}, p2 = {
                x = 6.72623263e-44, y = 1.90766944e-38}}, component = }}
        visible = true
#5  0x0000000000469b78 in Component::eventChild (this=this@entry=0x1182aa0, child=..., 
    event=..., visible=visible@entry=true) at ../../lincity-ng/src/gui/Component.cpp:101
        __PRETTY_FUNCTION__ = "bool Component::eventChild(Child&, const Event&, bool)"
        ev = {type = Event::MOUSEBUTTONUP, mousepos = {x = 1086, y = 60.777771}, mousemove = {
            x = 0, y = 0}, mousebutton = 1, keysym = {scancode = 64 '@', sym = SDLK_LALT, 
            mod = KMOD_NONE, unicode = 0}, inside = true, elapsedTime = 0.100000001}
#6  0x0000000000469c2c in Component::event (this=0x1182aa0, event=...)
    at ../../lincity-ng/src/gui/Component.cpp:114
        child = @0x15e7230: {position = {x = 0, y = 910.222229}, enabled = true, 
          useClipRect = false, clipRect = {p1 = {x = 0, y = 0}, p2 = {x = 0, y = 0}}, 
          component = 0x140e300}
        i = {<std::iterator<std::random_access_iterator_tag, Child, long, Child*, Child&>> = {<No data fields>}, current = {position = {x = 2.35098856e-38, y = 2.35098856e-38}, enabled = 255, 
            useClipRect = 255, clipRect = {p1 = {x = 2.35098856e-38, y = 2.35098856e-38}, p2 = {
                x = 2.35098856e-38, y = 2.35098856e-38}}, component = }}
        visible = true
#7  0x0000000000469b78 in Component::eventChild (this=this@entry=0x1182660, child=..., 
    event=..., visible=visible@entry=true) at ../../lincity-ng/src/gui/Component.cpp:101
        __PRETTY_FUNCTION__ = "bool Component::eventChild(Child&, const Event&, bool)"
        ev = {type = Event::MOUSEBUTTONUP, mousepos = {x = 1086, y = 971}, mousemove = {x = 0, 
            y = 0}, mousebutton = 1, keysym = {scancode = 64 '@', sym = SDLK_LALT, 
            mod = KMOD_NONE, unicode = 0}, inside = true, elapsedTime = 0.100000001}
#8  0x0000000000469c2c in Component::event (this=this@entry=0x1182660, event=...)
    at ../../lincity-ng/src/gui/Component.cpp:114
        child = @0x140af48: {position = {x = 0, y = 0}, enabled = true, useClipRect = false, 
          clipRect = {p1 = {x = 0, y = 0}, p2 = {x = 0, y = 0}}, component = 0x1182aa0}
        i = {<std::iterator<std::random_access_iterator_tag, Child, long, Child*, Child&>> = {<No data fields>}, current = {position = {x = 1.90576591e-43, y = 0}, enabled = 65, 
            useClipRect = false, clipRect = {p1 = {x = 0, y = 1.12235375e-38}, p2 = {
                x = 6.72623263e-44, y = 3.53907456e-38}}, component = }}
        visible = true
#9  0x000000000046807e in Desktop::event (this=0x1182660, event=...)
    at ../../lincity-ng/src/gui/Desktop.cpp:78
No locals.
#10 0x00000000004174a8 in MainMenu::run (this=this@entry=0xcf5860)
    at ../../lincity-ng/src/lincity-ng/MainMenu.cpp:1019
        gui_event = {type = Event::MOUSEBUTTONUP, mousepos = {x = 1086, y = 971}, mousemove = {
            x = 0, y = 0}, mousebutton = 1, keysym = {scancode = 64 '@', sym = SDLK_LALT, 
            mod = KMOD_NONE, unicode = 0}, inside = true, elapsedTime = 0.100000001}
        ticks = <optimized out>
        elapsedTime = <optimized out>
        event = {type = 6 '\006', active = {type = 6 '\006', gain = 0 '\000', state = 1 '\001'}, 
          key = {type = 6 '\006', which = 0 '\000', state = 1 '\001', keysym = {
              scancode = 62 '>', sym = SDLK_UNKNOWN, mod = KMOD_NONE, unicode = 0}}, motion = {
            type = 6 '\006', which = 0 '\000', state = 1 '\001', x = 1086, y = 971, xrel = 0, 
            yrel = 0}, button = {type = 6 '\006', which = 0 '\000', button = 1 '\001', 
            state = 0 '\000', x = 1086, y = 971}, jaxis = {type = 6 '\006', which = 0 '\000', 
            axis = 1 '\001', value = 1086}, jball = {type = 6 '\006', which = 0 '\000', 
            ball = 1 '\001', xrel = 1086, yrel = 971}, jhat = {type = 6 '\006', 
            which = 0 '\000', hat = 1 '\001', value = 0 '\000'}, jbutton = {type = 6 '\006', 
            which = 0 '\000', button = 1 '\001', state = 0 '\000'}, resize = {type = 6 '\006', 
            w = 63636542, h = 0}, expose = {type = 6 '\006'}, quit = {type = 6 '\006'}, user = {
            type = 6 '\006', code = 63636542, data1 = 0x0, data2 = 0x0}, syswm = {
            type = 6 '\006', msg = 0x0}}
        lastticks = <optimized out>
#11 0x0000000000459d45 in mainLoop () at ../../lincity-ng/src/lincity-ng/main.cpp:439
        game = {_M_ptr = 0x0}
        state = <optimized out>
        __PRETTY_FUNCTION__ = "void mainLoop()"
        menu = {_M_ptr = 0xcf5860}
        nextstate = <optimized out>
#12 0x000000000040a2c7 in main (argc=1, argv=0x7fffffffd248)
    at ../../lincity-ng/src/lincity-ng/main.cpp:608
        sound = {_M_ptr = 0xca90a0}
        result = 0
````

**Comment by Quix0r** [comment]
Never mind. I needed to "jam install" ... It was using old files with never engine. Now it works nicely. :)

**Comment by asl97** [comment]
@Quix0r please close this when you are able to, help keep the issue tracker neat.
